repos:
  - repo: local
    hooks:
      - id: check-config-headless
        name: Ensure headless = true in Streamlit config.toml
        entry: bash -c "grep -qE '^[[:space:]]*headless[[:space:]]*=[[:space:]]*true\\b' .streamlit/config.toml || (echo >&2 '⚠️  .streamlit/config.toml must contain headless = true'; exit 1)"
        language: system
        files: ^\.streamlit/config\.toml$
