repos:
  - repo: local
    hooks:
      - id: check-config-headless
        name: Ensure headless = true in Streamlit config.toml
        entry: grep -qE '^ *headless *= *true *$' .streamlit/config.toml
        language: system
        files: ^\.streamlit/config\.toml$
      - id: check-dummy-matchups
        name: Ensure USE_DUMMY_MATCHUPS = False in sideboarder.py
        entry: grep -qE '^ *USE_DUMMY_MATCHUPS *= *False *$' sideboarder.py
        language: system
        files: ^sideboarder\.py$
