name: sideboarder_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - matplotlib
  - pillow
  - pip

  # PyPI-only packages
  - pip:
    - pre-commit
    - streamlit
    - pytest
    - flake8
    - black