name: sideboarder_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - matplotlib
  - io
  - re
  - hashlib
  - json
  - datetime
  - pip
  - pip:
    - pre-commit
    - streamlit
    - pytest
    - flake8
    - black
