name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniconda & create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          environment-file: environment.yml
          activate-environment: sideboarder_env
          auto-update-conda: true

      - name: Debug conda env update
        shell: bash
        run: |
          # ensure we don’t have any interactive prompts
          conda config --set always_yes yes --set changeps1 no
          # this will print the full solver output and conflicts
          conda env update \
            --name sideboarder_env \
            --file ./environment.yml \
            --prune \
            --debug

      - name: Lint with black
        run: conda run -n sideboarder_env black --check .

      - name: Lint with flake8
        run: |
          conda run -n sideboarder_env flake8 \
            --ignore=E203,E501,W503,F401 \
            .

