name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniconda & create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          environment-file: environment.yml
          activate-environment: sideboarder_env
          auto-update-conda: true

      - name: Lint with black
        run: conda run -n sideboarder_env black --check .

      - name: Lint with flake8
        run: |
          conda run -n sideboarder_env flake8 \
            --ignore=E203,E501,W503,F401 \
            .

      - name: Run tests
        run: conda run -n sideboarder_env pytest --maxfail=1 --disable-warnings -q
