# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ← Replace the pip-based setup with Conda:
      - name: Setup Miniconda & create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'                # match your env
          environment-file: environment.yml     # points to your sideboarder_env spec
          activate-environment: sideboarder_env # name from env file
          auto-update-conda: true               # gets latest conda

      - name: Lint with black
        run: black --check .

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

