[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 1

[browser]
gatherUsageStats = true

[client] 
showSidebarNavigation = false

[theme]
primaryColor = "#AF5D63"
backgroundColor = "#181C14"
secondaryBackgroundColor = "#3C3D37"
textColor = "#ECDFCC"
linkColor = "#9DC7C8"
font = "sans-serif"
headingFont = "serif"
codeFont = "monospace"
showSidebarBorder = true