[server]
headless           = true
enableCORS         = false

[browser]
gatherUsageStats   = true

[theme]
base                     = "light"
primaryColor             = "#F63366"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor                = "#262730"
codeFont                 = "monospace"