[server]
headless           = false
enableCORS         = true

[browser]
gatherUsageStats   = true

[theme]
primaryColor             = "#697565"
backgroundColor          = "#181C14"
secondaryBackgroundColor = "#3C3D37"
textColor                = "#ECDFCC"
font                     = "sans-serif"
headingFont              = "serif"
codeFont                 = "monospace"